name: Sync Blockchain Data

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sync API
        run: |
          curl -X POST https://hypio-dashboard-lilac-tau.vercel.app/api/sync \
            -H "Content-Type: application/json" \
            -w "\nHTTP Status: %{http_code}\n" \
            || echo "Sync request failed"

      - name: Log completion
        run: echo "Blockchain sync completed at $(date)"
